global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'test'

remote_write:
    - url: http://cortex:9009/api/prom/push

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'cortex'
      static_configs:
        - targets: ['cortex:9009']
